module.exports = [
  {
    proyectname: 'Landing Page',
    description: 'some description',
    status: true,
    managerId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    proyectname: 'E-Commerce Shop',
    description: 'some description2',
    status: true,
    managerId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    proyectname: 'CRM Linkroom',
    description: 'some description3',
    status: false,
    managerId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    proyectname: 'Random proyect name 1',
    description: 'some description3',
    status: false,
    managerId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    proyectname: 'Random proyect name 2',
    description: 'some description3',
    status: false,
    managerId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    proyectname: 'Random proyect name 3',
    description: 'some description3',
    status: false,
    managerId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    proyectname: 'Random proyect name 4',
    description: 'some description3',
    status: false,
    managerId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    proyectname: 'Random proyect name 5',
    description: 'some description3',
    status: false,
    managerId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    proyectname: 'Random proyect name 6',
    description: 'some description3',
    status: false,
    managerId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    proyectname: 'Random proyect name 7',
    description: 'some description3',
    status: false,
    managerId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    proyectname: 'Random proyect name 8',
    description: 'some description3',
    status: false,
    managerId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    proyectname: 'Random proyect name 9',
    description: 'some description3',
    status: false,
    managerId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    proyectname: 'Random proyect name 10',
    description: 'some description3',
    status: false,
    managerId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
